<?php
//Database connection
define('DB_USERNAME','root');
define('DB_PASSWORD','');
define('DB_HOST','localhost');
define('DB_NAME','untukpati');

//Insert Result
define('SERVICE_TYPE_ADDED_SUCCESSFULLY', 0);
define('SERVICE_TYPE_ADD_FAILED', 1);
define('SERVICE_TYPE_ALREADY_EXISTED', 2);

define('SERVICE_DISTRICT_ADDED_SUCCESSFULLY', 0);
define('SERVICE_DISTRICT_ADD_FAILED', 1);
define('SERVICE_DISTRICT_ALREADY_EXISTED', 2);

define('SERVICE_ADDED_SUCCESSFULLY', 0);
define('SERVICE_ADD_FAILED', 1);
define('SERVICE_ALREADY_EXISTED', 2);

//Update Result
define('SERVICE_TYPE_UPDATED', 0);
define('SERVICE_TYPE_UPDATE_FAILED', 1);

define('SERVICE_DISTRICT_UPDATED', 0);
define('SERVICE_DISTRICT_UPDATE_FAILED', 1);

define('SERVICE_UPDATED', 0);
define('SERVICE_UPDATE_FAILED', 1);

//Delete Result
define('SERVICE_TYPE_DELETED', 0);
define('SERVICE_TYPE_DELETE_FAILED', 1);

define('SERVICE_DISTRICT_DELETED', 0);
define('SERVICE_DISTRICT_DELETE_FAILED', 1);

define('SERVICE_DELETED', 0);
define('SERVICE_DELETE_FAILED', 1);

//Not Exist
define('SERVICE_TYPE_NOT_EXIST', 2);
define('SERVICE_DISTRICT_NOT_EXIST', 2);
define('SERVICE_NOT_EXIST', 2);

?>
